@startuml crt.png

(*) --> "古いツールやプロセスを使っていて効率や品質が上がらない"
"古いツールやプロセスを使っていて効率や品質が上がらない" --> "勉強を開始する人とそうでない人が発生し、その間に技術格差が生まれる"
"古いツールや技術を使い続ける人が多数派で職制も高位なことが多い" --> "新しいツールや技術を勉強した人がそのツールや技術を導入しようとすると、労力がかかる"
"そのような人たちは新しいツールや技術の導入に懐疑的であったり、過剰にドキュメントを求めたりする" --> "新しいツールや技術を勉強した人がそのツールや技術を導入しようとすると、労力がかかる"

"新しいツールや技術を勉強した人がそのツールや技術を導入しようとすると、労力がかかる" --> "先進的な技術を知っている人ほど、その技術導入に多大な労力がかかるようになる"
"勉強を開始する人とそうでない人が発生し、その間に技術格差が生まれる" --> "技術格差が大きいほど、技術導入にかかる労力が大きくなる"
"技術格差が大きいほど、技術導入にかかる労力が大きくなる" --> "先進的な技術を知っている人ほど、その技術導入に多大な労力がかかるようになる"

"先進的な技術を知っている人ほど、その技術導入に多大な労力がかかるようになる" --> "技術導入をしなくなる"
"技術導入が正当に評価されていないと感じる" --> "技術導入をしなくなる"
"技術導入が正当に評価されていないと感じる" --> "技術を正当に評価する会社へ転職する"

"技術導入をしなくなる" --> "古いツールやプロセスを使っていて効率や品質が上がらない"
"技術導入をしなくなる" --> "技術保有者が技術を隠す"

@enduml
